version: '3.8'

services:
  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: lista_jogos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge